In [2]:
#Importing LIbraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
#Ques:1: reading the csv
df= pd.read_csv("https://raw.githubusercontent.com/Lordvarun23/MarketingAnalytics/main/Hotel%20Analysis/Sample%20hotel%20data.csv")

In [4]:
#Ques:2: Display the dataset
df.head()

,Hotel_Name_City,Review_Overall_Rating,date_of_review,Month_of_Visit,Review_Type,Rating_Value,Rating_Location,Rating_Sleep_Quality,Rating_Rooms,Rating_Cleanliness,Rating_Service
0,Bombay Hotel Jaipur,3,8/26/2014,Aug-14,with family,3.0,4.0,NaN,NaN,NaN,3.0
1,Bombay Hotel Jaipur,1,06-02-2013,Jun-13,NaN,1.0,2.0,NaN,1.0,1.0,3.0
2,Coffea Aroma Resort - Wayanad Meppadi,2,10/20/2014,Oct-14,with friends,2.0,NaN,NaN,2.0,NaN,1.0
3,Coffea Aroma Resort - Wayanad Meppadi,3,9/29/2014,Sep-14,with friends,NaN,4.0,NaN,NaN,3.0,3.0
4,Coffea Aroma Resort - Wayanad Meppadi,3,09-03-2014,Jul-14,as a couple,NaN,NaN,3.0,2.0,NaN,5.0

In [7]:
df.groupby('Hotel_Name_City').agg({('Review_Overall_Rating','Rating_Value'):'mean'})

KeyError: ignored